name: CODE_SCANNING

on:
  workflow_dispatch:
#  push:
#    branches: [ main, develop ]
#  pull_request:
#    branches: [ main, develop ]
#    paths-ignore:
#      - '**/*.md'

jobs:
  codeql_build:
    name: Scan with CodeQL

    # CodeQL runs on ubuntu-latest, windows-latest, and macos-latest
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@2892aa5e19bbd11bc0cff5427e3b750a04d9e3c2 # v4
        with:
          languages: javascript
          config: |
            paths-ignore:
              - '**/__tests__'
              - '**/test'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@2892aa5e19bbd11bc0cff5427e3b750a04d9e3c2 # v4

